-- Skillchain property data, derived from the Skillchains addon by Ivaar.
-- sc_info: for each open resonance property, maps a "closer" property name to
--   {level, resulting_chain_name}.  Indexed arrays give the element affinity of
--   that property (used by the Skillchains display; not used here).
-- weapon_skills: indexed by WS ID, {en=name, skillchain={props...}, delay=N}.
--   delay defaults to 3 seconds when absent.

local M = {}

M.sc_info = {
    Radiance     = {'Fire','Wind','Lightning','Light', lvl=4},
    Umbra        = {'Earth','Ice','Water','Dark',      lvl=4},
    Light        = {'Fire','Wind','Lightning','Light',
                    Light={4,'Light','Radiance'}, lvl=3},
    Darkness     = {'Earth','Ice','Water','Dark',
                    Darkness={4,'Darkness','Umbra'}, lvl=3},
    Gravitation  = {'Earth','Dark',
                    Distortion={3,'Darkness'}, Fragmentation={2,'Fragmentation'}, lvl=2},
    Fragmentation= {'Wind','Lightning',
                    Fusion={3,'Light'}, Distortion={2,'Distortion'}, lvl=2},
    Distortion   = {'Ice','Water',
                    Gravitation={3,'Darkness'}, Fusion={2,'Fusion'}, lvl=2},
    Fusion       = {'Fire','Light',
                    Fragmentation={3,'Light'}, Gravitation={2,'Gravitation'}, lvl=2},
    Compression  = {'Darkness',
                    Transfixion={1,'Transfixion'}, Detonation={1,'Detonation'}, lvl=1},
    Liquefaction = {'Fire',
                    Impaction={2,'Fusion'}, Scission={1,'Scission'}, lvl=1},
    Induration   = {'Ice',
                    Reverberation={2,'Fragmentation'}, Compression={1,'Compression'},
                    Impaction={1,'Impaction'}, lvl=1},
    Reverberation= {'Water',
                    Induration={1,'Induration'}, Impaction={1,'Impaction'}, lvl=1},
    Transfixion  = {'Light',
                    Scission={2,'Distortion'}, Reverberation={1,'Reverberation'},
                    Compression={1,'Compression'}, lvl=1},
    Scission     = {'Earth',
                    Liquefaction={1,'Liquefaction'}, Reverberation={1,'Reverberation'},
                    Detonation={1,'Detonation'}, lvl=1},
    Detonation   = {'Wind',
                    Compression={2,'Gravitation'}, Scission={1,'Scission'}, lvl=1},
    Impaction    = {'Lightning',
                    Liquefaction={1,'Liquefaction'}, Detonation={1,'Detonation'}, lvl=1},
}

-- Weapon skill ID -> {en, skillchain, [delay]}
M.weapon_skills = {
    [1]  = {en='Combo',             skillchain={'Impaction'}},
    [2]  = {en='Shoulder Tackle',   skillchain={'Reverberation','Impaction'}},
    [3]  = {en='One Inch Punch',    skillchain={'Compression'}},
    [4]  = {en='Backhand Blow',     skillchain={'Detonation'}},
    [5]  = {en='Raging Fists',      skillchain={'Impaction'}},
    [6]  = {en='Spinning Attack',   skillchain={'Liquefaction','Impaction'}},
    [7]  = {en='Howling Fist',      skillchain={'Transfixion','Impaction'}},
    [8]  = {en='Dragon Kick',       skillchain={'Fragmentation'}},
    [9]  = {en='Asuran Fists',      skillchain={'Gravitation','Liquefaction'}},
    [10] = {en='Final Heaven',      skillchain={'Light','Fusion'}},
    [11] = {en="Ascetic's Fury",    skillchain={'Fusion','Transfixion'}},
    [12] = {en='Stringing Pummel',  skillchain={'Gravitation','Liquefaction'}},
    [13] = {en='Tornado Kick',      skillchain={'Induration','Detonation','Impaction'}},
    [14] = {en='Victory Smite',     skillchain={'Light','Fragmentation'}},
    [15] = {en='Shijin Spiral',     skillchain={'Fusion','Reverberation'}},
    [16] = {en='Wasp Sting',        skillchain={'Scission'}},
    [17] = {en='Viper Bite',        skillchain={'Scission'}},
    [18] = {en='Shadowstitch',      skillchain={'Reverberation'}},
    [19] = {en='Gust Slash',        skillchain={'Detonation'}},
    [20] = {en='Cyclone',           skillchain={'Detonation','Impaction'}},
    [23] = {en='Dancing Edge',      skillchain={'Scission','Detonation'}},
    [24] = {en='Shark Bite',        skillchain={'Fragmentation'}},
    [25] = {en='Evisceration',      skillchain={'Gravitation','Transfixion'}},
    [26] = {en='Mercy Stroke',      skillchain={'Darkness','Gravitation'}},
    [27] = {en='Mandalic Stab',     skillchain={'Fusion','Compression'}},
    [28] = {en='Mordant Rime',      skillchain={'Fragmentation','Distortion'}},
    [29] = {en='Pyrrhic Kleos',     skillchain={'Distortion','Scission'}},
    [30] = {en='Aeolian Edge',      skillchain={'Scission','Detonation','Impaction'}},
    [31] = {en="Rudra's Storm",     skillchain={'Darkness','Distortion'}},
    [32] = {en='Fast Blade',        skillchain={'Scission'}},
    [33] = {en='Burning Blade',     skillchain={'Liquefaction'}},
    [34] = {en='Red Lotus Blade',   skillchain={'Liquefaction','Detonation'}},
    [35] = {en='Flat Blade',        skillchain={'Impaction'}},
    [36] = {en='Shining Blade',     skillchain={'Scission'}},
    [37] = {en='Seraph Blade',      skillchain={'Scission'}},
    [38] = {en='Circle Blade',      skillchain={'Reverberation','Impaction'}},
    [40] = {en='Vorpal Blade',      skillchain={'Scission','Impaction'}},
    [41] = {en='Swift Blade',       skillchain={'Gravitation'}},
    [42] = {en='Savage Blade',      skillchain={'Fragmentation','Scission'}},
    [43] = {en='Knights of Round',  skillchain={'Light','Fusion'}},
    [44] = {en='Death Blossom',     skillchain={'Fragmentation','Distortion'}},
    [45] = {en='Atonement',         skillchain={'Fusion','Reverberation'}},
    [46] = {en='Expiacion',         skillchain={'Distortion','Scission'}},
    [48] = {en='Hard Slash',        skillchain={'Scission'}},
    [49] = {en='Power Slash',       skillchain={'Transfixion'}},
    [50] = {en='Frostbite',         skillchain={'Induration'}},
    [51] = {en='Freezebite',        skillchain={'Induration','Detonation'}},
    [52] = {en='Shockwave',         skillchain={'Reverberation'}},
    [53] = {en='Crescent Moon',     skillchain={'Scission'}},
    [54] = {en='Sickle Moon',       skillchain={'Scission','Impaction'}},
    [55] = {en='Spinning Slash',    skillchain={'Fragmentation'}},
    [56] = {en='Ground Strike',     skillchain={'Fragmentation','Distortion'}},
    [57] = {en='Scourge',           skillchain={'Light','Fusion'}},
    [58] = {en='Herculean Slash',   skillchain={'Induration','Detonation','Impaction'}},
    [59] = {en='Torcleaver',        skillchain={'Light','Distortion'}},
    [60] = {en='Resolution',        skillchain={'Fragmentation','Scission'}},
    [61] = {en='Dimidiation',       skillchain={'Light','Fragmentation'}},
    [64] = {en='Raging Axe',        skillchain={'Detonation','Impaction'}},
    [65] = {en='Smash Axe',         skillchain={'Induration','Reverberation'}},
    [66] = {en='Gale Axe',          skillchain={'Detonation'}},
    [67] = {en='Avalanche Axe',     skillchain={'Scission','Impaction'}},
    [68] = {en='Spinning Axe',      skillchain={'Liquefaction','Scission','Impaction'}},
    [69] = {en='Rampage',           skillchain={'Scission'}},
    [70] = {en='Calamity',          skillchain={'Scission','Impaction'}},
    [71] = {en='Mistral Axe',       skillchain={'Fusion'}},
    [72] = {en='Decimation',        skillchain={'Fusion','Reverberation'}},
    [73] = {en='Onslaught',         skillchain={'Darkness','Gravitation'}},
    [74] = {en='Primal Rend',       skillchain={'Gravitation','Reverberation'}},
    [75] = {en='Bora Axe',          skillchain={'Scission','Detonation'}},
    [76] = {en='Cloudsplitter',     skillchain={'Darkness','Fragmentation'}},
    [77] = {en='Ruinator',          skillchain={'Distortion','Detonation'}},
    [80] = {en='Shield Break',      skillchain={'Impaction'}},
    [81] = {en='Iron Tempest',      skillchain={'Scission'}},
    [82] = {en='Sturmwind',         skillchain={'Reverberation','Scission'}},
    [83] = {en='Armor Break',       skillchain={'Impaction'}},
    [84] = {en='Keen Edge',         skillchain={'Compression'}},
    [85] = {en='Weapon Break',      skillchain={'Impaction'}},
    [86] = {en='Raging Rush',       skillchain={'Induration','Reverberation'}},
    [87] = {en='Full Break',        skillchain={'Distortion'}},
    [88] = {en='Steel Cyclone',     skillchain={'Distortion','Detonation'}},
    [89] = {en='Metatron Torment',  skillchain={'Light','Fusion'}},
    [90] = {en="King's Justice",    skillchain={'Fragmentation','Scission'}},
    [91] = {en='Fell Cleave',       skillchain={'Scission','Detonation','Impaction'}},
    [92] = {en="Ukko's Fury",       skillchain={'Light','Fragmentation'}},
    [93] = {en='Upheaval',          skillchain={'Fusion','Compression'}},
    [96] = {en='Slice',             skillchain={'Scission'}},
    [97] = {en='Dark Harvest',      skillchain={'Reverberation'}},
    [98] = {en='Shadow of Death',   skillchain={'Induration','Reverberation'}},
    [99] = {en='Nightmare Scythe',  skillchain={'Compression','Scission'}},
    [100]= {en='Spinning Scythe',   skillchain={'Reverberation','Scission'}},
    [101]= {en='Vorpal Scythe',     skillchain={'Transfixion','Scission'}},
    [102]= {en='Guillotine',        skillchain={'Induration'}},
    [103]= {en='Cross Reaper',      skillchain={'Distortion'}},
    [104]= {en='Spiral Hell',       skillchain={'Distortion','Scission'}},
    [105]= {en='Catastrophe',       skillchain={'Darkness','Gravitation'}},
    [106]= {en='Insurgency',        skillchain={'Fusion','Compression'}},
    [107]= {en='Infernal Scythe',   skillchain={'Compression','Reverberation'}},
    [108]= {en='Quietus',           skillchain={'Darkness','Distortion'}},
    [109]= {en='Entropy',           skillchain={'Gravitation','Reverberation'}},
    [112]= {en='Double Thrust',     skillchain={'Transfixion'}},
    [113]= {en='Thunder Thrust',    skillchain={'Transfixion','Impaction'}},
    [114]= {en='Raiden Thrust',     skillchain={'Transfixion','Impaction'}},
    [115]= {en='Leg Sweep',         skillchain={'Impaction'}},
    [116]= {en='Penta Thrust',      skillchain={'Compression'}},
    [117]= {en='Vorpal Thrust',     skillchain={'Reverberation','Transfixion'}},
    [118]= {en='Skewer',            skillchain={'Transfixion','Impaction'}},
    [119]= {en='Wheeling Thrust',   skillchain={'Fusion'}},
    [120]= {en='Impulse Drive',     skillchain={'Gravitation','Induration'}},
    [121]= {en='Geirskogul',        skillchain={'Light','Distortion'}},
    [122]= {en='Drakesbane',        skillchain={'Fusion','Transfixion'}},
    [123]= {en='Sonic Thrust',      skillchain={'Transfixion','Scission'}},
    [124]= {en="Camlann's Torment", skillchain={'Light','Fragmentation'}},
    [125]= {en='Stardiver',         skillchain={'Gravitation','Transfixion'}},
    [128]= {en='Blade: Rin',        skillchain={'Transfixion'}},
    [129]= {en='Blade: Retsu',      skillchain={'Scission'}},
    [130]= {en='Blade: Teki',       skillchain={'Reverberation'}},
    [131]= {en='Blade: To',         skillchain={'Induration','Detonation'}},
    [132]= {en='Blade: Chi',        skillchain={'Transfixion','Impaction'}},
    [133]= {en='Blade: Ei',         skillchain={'Compression'}},
    [134]= {en='Blade: Jin',        skillchain={'Detonation','Impaction'}},
    [135]= {en='Blade: Ten',        skillchain={'Gravitation'}},
    [136]= {en='Blade: Ku',         skillchain={'Gravitation','Transfixion'}},
    [137]= {en='Blade: Metsu',      skillchain={'Darkness','Fragmentation'}},
    [138]= {en='Blade: Kamu',       skillchain={'Fragmentation','Compression'}},
    [139]= {en='Blade: Yu',         skillchain={'Reverberation','Scission'}},
    [140]= {en='Blade: Hi',         skillchain={'Darkness','Gravitation'}},
    [141]= {en='Blade: Shun',       skillchain={'Fusion','Impaction'}},
    [144]= {en='Tachi: Enpi',       skillchain={'Transfixion','Scission'}},
    [145]= {en='Tachi: Hobaku',     skillchain={'Induration'}},
    [146]= {en='Tachi: Goten',      skillchain={'Transfixion','Impaction'}},
    [147]= {en='Tachi: Kagero',     skillchain={'Liquefaction'}},
    [148]= {en='Tachi: Jinpu',      skillchain={'Scission','Detonation'}},
    [149]= {en='Tachi: Koki',       skillchain={'Reverberation','Impaction'}},
    [150]= {en='Tachi: Yukikaze',   skillchain={'Induration','Detonation'}},
    [151]= {en='Tachi: Gekko',      skillchain={'Distortion','Reverberation'}},
    [152]= {en='Tachi: Kasha',      skillchain={'Fusion','Compression'}},
    [153]= {en='Tachi: Kaiten',     skillchain={'Light','Fragmentation'}},
    [154]= {en='Tachi: Rana',       skillchain={'Gravitation','Induration'}},
    [155]= {en='Tachi: Ageha',      skillchain={'Compression','Scission'}},
    [156]= {en='Tachi: Fudo',       skillchain={'Light','Distortion'}},
    [157]= {en='Tachi: Shoha',      skillchain={'Fragmentation','Compression'}},
    [158]= {en='Tachi: Suikawari',  skillchain={'Fusion'}},
    [160]= {en='Shining Strike',    skillchain={'Impaction'}},
    [161]= {en='Seraph Strike',     skillchain={'Impaction'}},
    [162]= {en='Brainshaker',       skillchain={'Reverberation'}},
    [165]= {en='Skullbreaker',      skillchain={'Induration','Reverberation'}},
    [166]= {en='True Strike',       skillchain={'Detonation','Impaction'}},
    [167]= {en='Judgment',          skillchain={'Impaction'}},
    [168]= {en='Hexa Strike',       skillchain={'Fusion'}},
    [169]= {en='Black Halo',        skillchain={'Fragmentation','Compression'}},
    [170]= {en='Randgrith',         skillchain={'Light','Fragmentation'}},
    [172]= {en='Flash Nova',        skillchain={'Induration','Reverberation'}},
    [174]= {en='Realmrazer',        skillchain={'Fusion','Impaction'}},
    [175]= {en='Exudation',         skillchain={'Darkness','Fragmentation'}},
    [176]= {en='Heavy Swing',       skillchain={'Impaction'}},
    [177]= {en='Rock Crusher',      skillchain={'Impaction'}},
    [178]= {en='Earth Crusher',     skillchain={'Detonation','Impaction'}},
    [179]= {en='Starburst',         skillchain={'Compression','Reverberation'}},
    [180]= {en='Sunburst',          skillchain={'Compression','Reverberation'}},
    [181]= {en='Shell Crusher',     skillchain={'Detonation'}},
    [182]= {en='Full Swing',        skillchain={'Liquefaction','Impaction'}},
    [184]= {en='Retribution',       skillchain={'Gravitation','Reverberation'}},
    [185]= {en='Gate of Tartarus',  skillchain={'Darkness','Distortion'}},
    [186]= {en='Vidohunir',         skillchain={'Fragmentation','Distortion'}},
    [187]= {en='Garland of Bliss',  skillchain={'Fusion','Reverberation'}},
    [188]= {en='Omniscience',       skillchain={'Gravitation','Transfixion'}},
    [189]= {en='Cataclysm',         skillchain={'Compression','Reverberation'}},
    [191]= {en='Shattersoul',       skillchain={'Gravitation','Induration'}},
    [192]= {en='Flaming Arrow',     skillchain={'Liquefaction','Transfixion'}},
    [193]= {en='Piercing Arrow',    skillchain={'Reverberation','Transfixion'}},
    [194]= {en='Dulling Arrow',     skillchain={'Liquefaction','Transfixion'}},
    [196]= {en='Sidewinder',        skillchain={'Reverberation','Transfixion','Detonation'}},
    [197]= {en='Blast Arrow',       skillchain={'Induration','Transfixion'}},
    [198]= {en='Arching Arrow',     skillchain={'Fusion'}},
    [199]= {en='Empyreal Arrow',    skillchain={'Fusion','Transfixion'}},
    [200]= {en='Namas Arrow',       skillchain={'Light','Distortion'}},
    [201]= {en='Refulgent Arrow',   skillchain={'Reverberation','Transfixion'}},
    [202]= {en="Jishnu's Radiance", skillchain={'Light','Fusion'}},
    [203]= {en='Apex Arrow',        skillchain={'Fragmentation','Transfixion'}},
    [208]= {en='Hot Shot',          skillchain={'Liquefaction','Transfixion'}},
    [209]= {en='Split Shot',        skillchain={'Reverberation','Transfixion'}},
    [210]= {en='Sniper Shot',       skillchain={'Liquefaction','Transfixion'}},
    [212]= {en='Slug Shot',         skillchain={'Reverberation','Transfixion','Detonation'}},
    [213]= {en='Blast Shot',        skillchain={'Induration','Transfixion'}},
    [214]= {en='Heavy Shot',        skillchain={'Fusion'}},
    [215]= {en='Detonator',         skillchain={'Fusion','Transfixion'}},
    [216]= {en='Coronach',          skillchain={'Darkness','Fragmentation'}},
    [217]= {en='Trueflight',        skillchain={'Fragmentation','Scission'}},
    [218]= {en='Leaden Salute',     skillchain={'Gravitation','Transfixion'}},
    [219]= {en='Numbing Shot',      skillchain={'Induration','Detonation','Impaction'}},
    [220]= {en='Wildfire',          skillchain={'Darkness','Gravitation'}},
    [221]= {en='Last Stand',        skillchain={'Fusion','Reverberation'}},
    [224]= {en='Exenterator',       skillchain={'Fragmentation','Scission'}},
    [225]= {en='Chant du Cygne',    skillchain={'Light','Distortion'}},
    [226]= {en='Requiescat',        skillchain={'Gravitation','Scission'}},
    [227]= {en="Knights of Rotund", skillchain={'Light'}},
    [228]= {en='Final Paradise',    skillchain={'Light'}},
    [238]= {en='Uriel Blade',       skillchain={'Light','Fragmentation'}},
    [239]= {en='Glory Slash',       skillchain={'Light','Fusion'}},
}

-- Build a name-indexed reverse lookup for fast access by WS name.
M.ws_by_name = {}
for id, data in pairs(M.weapon_skills) do
    M.ws_by_name[data.en:lower()] = {id=id, skillchain=data.skillchain, delay=data.delay or 3}
end

return M
